### ISSUE TITLE
Elm v0.19

### ISSUE THREAD

**Issue by ghost** [yotamDvir/elm-katex#1]
Do you have any plans to update this project to Elm v0.19? Thanks!

**Comment by yotamDvir** [comment]
Forgot this existed to be honest.

I will happily accept a pull-request to update. Maybe I'll find time to do this myself, although I can't make any promises.

**Comment by ghost** [comment]
No problem. I can look into updating this project as well. I will submit a PR if I get a chance. Thanks!

**Comment by ghost** [comment]
Just submitted PR #2
